services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: us.gcr.io/teamgs/teamgs_web:latest
    container_name: teamgs_web
    restart: always
    ports:
      - "8000:8000"
    links: 
      - redis

  channels:
    build: 
      context: .
      dockerfile: Dockerfile-channels
    image: us.gcr.io/teamgs/teamgs_channels:latest
    container_name: teamgs_channels
    restart: always
    ports: 
      - "8001:8001"
    links:
      - redis
  
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    image: us.gcr.io/teamgs/teamgs_nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - web
      - channels
    ports:
     - "80:80"