# Generated by Django 4.2.5 on 2023-10-03 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=150)),
                ('retrieval_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['retrieval_date'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('region', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NBAArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nba.article')),
                ('association', models.CharField(default='NBA', max_length=3)),
            ],
            bases=('nba.article',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('teamID', models.IntegerField()),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('losses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win_pct', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('logo', models.ImageField(max_length=255, upload_to='')),
                ('last_updated', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('conference', models.ForeignKey(blank=True, db_column='conference', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_conference', to='nba.conference')),
                ('liked_by', models.ManyToManyField(blank=True, default=None, related_name='%(class)s_liked_nba_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('height_feet', models.PositiveSmallIntegerField(null=True)),
                ('height_inches', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('jersey_number', models.PositiveSmallIntegerField(null=True)),
                ('position', models.CharField(max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_team_points', models.IntegerField(blank=True, null=True)),
                ('away_team_points', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='nba.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='nba.team')),
            ],
            options={
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TeamArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nba.article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.team')),
            ],
            bases=('nba.article',),
        ),
    ]
