# Generated by Django 3.0.9 on 2022-03-28 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('teamID', models.IntegerField()),
                ('conference', models.CharField(max_length=4)),
                ('wins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('losses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win_pct', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('liked_by', models.ManyToManyField(blank=True, default=None, related_name='team_liked_nba_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('conference', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=4)),
                ('home_team_points', models.IntegerField(blank=True, null=True)),
                ('away_team_points', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='nba.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='nba.Team')),
            ],
            options={
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=100)),
                ('retrieval_date', models.DateField(blank=True, default=datetime.date.today)),
                ('team', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='nba.Team')),
            ],
            options={
                'get_latest_by': ['retrieval_date'],
            },
        ),
    ]
