# Generated by Django 3.0.9 on 2022-03-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba.Team'),
        ),
    ]
