# Generated by Django 3.0.9 on 2022-03-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_auto_20220328_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='teams',
        ),
        migrations.AddField(
            model_name='standing',
            name='teams',
            field=models.ManyToManyField(null=True, to='nba.Team'),
        ),
    ]
