# Generated by Django 3.0.9 on 2022-03-29 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_auto_20220328_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Standing',
        ),
    ]
