# Generated by Django 3.0.9 on 2022-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_auto_20220328_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
