# Generated by Django 3.0.9 on 2022-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_auto_20220407_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='win_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
