# Generated by Django 3.0.9 on 2023-01-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=100)),
                ('retrieval_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['retrieval_date'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('teamID', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.League')),
                ('liked_by', models.ManyToManyField(blank=True, default=None, related_name='team_liked_soccer_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('height_feet', models.PositiveSmallIntegerField(null=True)),
                ('height_inches', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('nationality', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField(null=True)),
                ('position', models.CharField(max_length=1, null=True)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccer.Article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Team')),
            ],
            bases=('soccer.article',),
        ),
        migrations.CreateModel(
            name='LeagueArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccer.Article')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.League')),
            ],
            bases=('soccer.article',),
        ),
    ]
