# Generated by Django 3.0.9 on 2022-03-28 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('leagueID', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('teamID', models.IntegerField()),
                ('leagueID', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('liked_by', models.ManyToManyField(blank=True, default=None, related_name='team_liked_soccer_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=100)),
                ('retrieval_date', models.DateField(blank=True, default=datetime.date.today)),
                ('team', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Team')),
            ],
            options={
                'get_latest_by': ['retrieval_date'],
            },
        ),
    ]
